export const site = {
  title: 'teclado',
  subtitle: 'notes from the desk',
  author: 'teclado',
  description: 'teclado 的书桌。读书、生活、正在做的事。',
  website: 'https://blog.teclado.cn',
  email: 'mailto:tecladochen@qq.com',
  umamiId: 'cdea5eb4-dd22-42aa-926a-b3b97c891417',
  icp: {
    text: '浙ICP备2023044092号-3',
    href: 'https://beian.miit.gov.cn/',
  },
  social: [
    { name: 'mail', href: 'mailto:tecladochen@qq.com' },
    { name: 'github', href: 'https://github.com/tecladochen' },
    { name: 'bilibili', href: 'https://space.bilibili.com/297265384' },
    { name: 'rss', href: '/atom.xml' },
  ],
  nav: [
    { name: 'index', href: '/' },
    { name: 'notes', href: '/writing/' },
    { name: 'about', href: '/about/' },
  ],
  ticker: ['write', 'read', 'hangzhou', 'teclado', 'slow notes', 'desk', 'out of yanjin'],
  quote: {
    text: '我想每个人都能从杨百顺身上看到自己看到无奈。',
    source: '读《出延津记》',
  },
  now: {
    kicker: 'now',
    title: '杭州',
    body: '创业团队做 AI 产品。桌上还摊着刘震云，和一场软考。',
  },
  marks: [
    {
      date: '2024-04-17',
      year: '2024',
      title: '结束嘉兴工作，搬来杭州',
      summary: '从后端开发转成了全栈，全栈说白了就是全干。',
    },
    {
      date: '2026-05-14',
      year: '2026',
      title: '裸辞后加入初创团队，做AI产品研发',
      summary: '有机会，也有挑战，能做的就是把握机会、迎接挑战。',
    },
    {
      date: '2026-08-04',
      year: '2026',
      title: '开始备考软考高级架构师',
      summary: '去年考过一次，这回留给自己两个月冲一遍。',
    },
  ],
  desk: [
    {
      no: '02',
      kicker: 'draft',
      title: '回延津记',
      excerpt: '下篇还没翻开。上篇写完之后，人还停在延津的土路上。',
      year: 'soon',
    },
    {
      no: '03',
      kicker: 'note',
      title: '杭州的雨',
      excerpt: '搬来之后雨声更密。窗关着，键盘还是潮的。',
      year: '2026',
    },
    {
      no: '04',
      kicker: 'studio',
      title: '想得太多',
      excerpt: '清单很长，动手总慢半拍。这是正在改的习惯。',
      year: '—',
    },
    {
      no: '05',
      kicker: 'play',
      title: '洛克王国',
      excerpt: '工作之外找回童心的方式，不算正经，但要留着。',
      year: '—',
    },
    {
      no: '06',
      kicker: 'exam',
      title: '纸面与机考',
      excerpt: '两个月，再冲一遍架构师。手要比脑子先热。',
      year: '2026',
    },
    {
      no: '07',
      kicker: 'wish',
      title: '还想做的事',
      excerpt: '乐器、游戏、vlog、英语、一点理财。先写在桌上。',
      year: '—',
    },
  ],
  materials: [
    {
      no: 'A',
      kind: 'listening',
      title: '夜里的键盘',
      note: '还没写成声音。先占一格。',
    },
    {
      no: 'B',
      kind: 'watching',
      title: '延津的土路',
      note: '书里的画面比窗外更远。',
    },
    {
      no: 'C',
      kind: 'making',
      title: '这个站',
      note: '从模板里拆出来，正在长成自己的形状。',
    },
    {
      no: 'D',
      kind: 'collecting',
      title: '空着的格子',
      note: '想做的比做成的多。空着难看，先把形状摆出来。',
    },
  ],
} as const
